version: "2.3"
services:
  nginx:
    ports:
      - "80:80"
  api-server:
    build:
      context: ./backend
      args:
        NODE_ENV: development
    volumes:
      - ./backend:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}

    command: npm run dev
