version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  
  api-server:
    build: ./backend
    image: api-server
    environment:
      - PORT=4000
    networks:
      - foobar-api
    # ports:
    #   - "4000:4000"
  rabbitmq:
    image: "rabbitmq"
    restart: always
    networks:
      - foobar-api

  redis-server:
    image: "redis"
    restart: always
    networks:
      - foobar-api

  code-engine-server:
    build: ./code-engine
    restart: always
    ports:
      - "5001:5001"
    networks:
      - foobar-api

  code-engine-worker:
    build: ./code-engine-workers
    restart: always
    pids_limit: 60 # Max number of processes running in thw container.
    cpus: 1 # No of CPUs allocated
    mem_limit: 150M # Hard limit
    networks:
      - foobar-api

  foobar-app:
    build: ./frontend
    image: foobar-app
    environment:
      - PORT=3000
    ports:
      - 3000:80
    depends_on:
      - nginx
    networks:
      - foobar-api

networks:
  foobar-api:
    driver: bridge