version: "3"
services:
  # nginx:
  #   image: nginx:stable-alpine
  #   restart: always
  #   depends_on:
  #       - api-server
  #       - foobar-app
  #   volumes:
  #       - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #      - 80:80
  #   networks:
  #      - foobar-api
  
  api-server:
    restart: always
    build:
      context: ./backend
      args:
        NODE_ENV: production  
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    command: npm start
    # ports:
    #   - "4000:4000"
    networks:
      - foobar-api
  rabbitmq:
    image: "rabbitmq"
    restart: always
    networks:
      - foobar-api

  redis-server:
    image: "redis"
    restart: always
    networks:
      - foobar-api

  code-engine-server:
    build: ./code-engine
    restart: always
    ports:
      - "5001:5001"
    networks:
      - foobar-api

  code-engine-worker:
    build: ./code-engine-workers
    restart: always
    pids_limit: 60 # Max number of processes running in thw container.
    cpus: 1 # No of CPUs allocated
    mem_limit: 150M # Hard limit
    networks:
      - foobar-api

  foobar-app:
    restart: always
    build: ./frontend
    # image: foobar-app
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - api-server
    networks:
      - foobar-api

networks:
  foobar-api:
    driver: bridge