version: "2.3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  
  api-server:
    build: ./backend
    image: api-server
    environment:
      - PORT=4000

  rabbitmq:
    image: "rabbitmq"
    restart: always
  redis-server:
    image: "redis"
    restart: always
  server:
    build: ./code-engine
    restart: always
    ports:
      - "5001:5001"
  worker:
    build: ./code-engine-workers
    restart: always
    pids_limit: 60 # Max number of processes running in thw container.
    cpus: 1 # No of CPUs allocated
    mem_limit: 150M # Hard limit

  # foobar-app:
  #   build: .
  #   image: foobar-app
  #   environment:
  #     - PORT=3000
