version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  
  api-server:
    image: api-server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      
  foobar-app:
    build: .
    image: foobar-app
    environment:
      - PORT=3000
