version: "3"
services:
  nginx:
    ports:
      - "80:80"
  foobar-app:
    deploy:
      replicas: 4
      restart_policy:
        condition: any
        max_attempts: 3
      update_config:
        parallelism: 2
        failure_action: rollback
        delay: 10s
    build:
      context: .
      args:
        NODE_ENV: production  
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    command: npm start
