version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  foobar-app:
    build: .
    # image: daysond/node-app
    environment:
      - PORT=3000

